version: "3.9"
services:
  api:
    build: .
    container_name: fastapi_app_prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres_db_prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    expose:
      - "5432"

  haproxy:
    image: haproxy:latest
    container_name: haproxy_prod
    restart: unless-stopped
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    ports:
      - "80:80"
      - "8404:8404"
    depends_on:
      - api

volumes:
  postgres_data_prod:
